import {
  type RuleLedgerEntry,
  type RuleProfile,
  validateRuleLedger,
} from "./schema.js";

const DOCS = "https://oxc.rs/docs/guide/usage/linter/rules";
const PREDECESSOR =
  "https://github.com/sebastian-software/eslint-config-setup";

function fixture(
  profile: RuleProfile,
  line: number,
  column: number,
  extension = "ts",
): RuleLedgerEntry["fixtures"] {
  return [
    {
      valid: `fixtures/rules/${profile}/valid.${extension}`,
      invalid: `fixtures/rules/${profile}/invalid.${extension}`,
      diagnostic: { line, column },
    },
  ];
}

function source(id: string): RuleLedgerEntry["source"] {
  const [plugin, rule] = id.split("/");
  return {
    documentation: `${DOCS}/${plugin?.replace("jsx-a11y", "jsx_a11y")}/${rule}.html`,
    predecessor: PREDECESSOR,
  };
}

const entries = [
  {
    id: "eslint/no-debugger",
    defectClass: "debugger statements committed to production code",
    profile: "core",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "A committed breakpoint changes runtime behavior and can expose internals.",
    source: source("eslint/no-debugger"),
    fixtures: fixture("core", 1, 1),
    replaces: ["eslint/no-debugger"],
    conflicts: [],
    reviewTrigger: "Review if Oxlint changes debugger-statement parsing or defaults.",
  },
  {
    id: "eslint/no-dupe-keys",
    defectClass: "overwritten object literal properties",
    profile: "core",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Duplicate keys silently discard an earlier value.",
    source: source("eslint/no-dupe-keys"),
    fixtures: fixture("core", 3, 27),
    replaces: ["eslint/no-dupe-keys"],
    conflicts: [],
    reviewTrigger: "Review if JavaScript changes duplicate-key semantics.",
  },
  {
    id: "eslint/no-unsafe-finally",
    defectClass: "control flow that suppresses try or catch completion",
    profile: "core",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Return or throw in finally silently replaces the original result or error.",
    source: source("eslint/no-unsafe-finally"),
    fixtures: fixture("core", 9, 5),
    replaces: ["eslint/no-unsafe-finally"],
    conflicts: [],
    reviewTrigger: "Review if Oxlint changes control-flow analysis for finally blocks.",
  },
  {
    id: "eslint/valid-typeof",
    defectClass: "misspelled typeof comparison values",
    profile: "core",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Invalid typeof strings make a branch permanently false.",
    source: source("eslint/valid-typeof"),
    fixtures: fixture("core", 14, 27),
    replaces: ["eslint/valid-typeof"],
    conflicts: [],
    reviewTrigger: "Review when JavaScript adds a new typeof result.",
  },
  {
    id: "import/no-duplicates",
    defectClass: "duplicate imports from one module",
    profile: "imports",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "One import declaration per module prevents split ownership and noisy diffs.",
    source: source("import/no-duplicates"),
    fixtures: fixture("imports", 2, 30),
    replaces: ["eslint/no-duplicate-imports", "eslint-plugin-import/no-duplicates"],
    conflicts: ["eslint/no-duplicate-imports"],
    reviewTrigger: "Review when the native rule subsumes type-only import edge cases.",
  },
  {
    id: "import/no-self-import",
    defectClass: "modules importing themselves",
    profile: "imports",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Self imports indicate a mistaken path and can create partial initialization.",
    source: source("import/no-self-import"),
    fixtures: fixture("imports", 1, 25),
    replaces: ["eslint-plugin-import/no-self-import"],
    conflicts: [],
    reviewTrigger: "Review if import resolution behavior changes.",
  },
  {
    id: "typescript/ban-ts-comment",
    defectClass: "unexplained TypeScript diagnostic suppression",
    profile: "typescript-syntax",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Type suppressions must use an expected-error directive with an explanation.",
    source: source("typescript/ban-ts-comment"),
    fixtures: fixture("typescript-syntax", 1, 3),
    replaces: ["@typescript-eslint/ban-ts-comment"],
    conflicts: [],
    reviewTrigger: "Review when TypeScript introduces new diagnostic directives.",
  },
  {
    id: "typescript/no-duplicate-enum-values",
    defectClass: "ambiguous duplicate enum values",
    profile: "typescript-syntax",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Duplicate enum values make reverse mapping and intent ambiguous.",
    source: source("typescript/no-duplicate-enum-values"),
    fixtures: fixture("typescript-syntax", 6, 10),
    replaces: ["@typescript-eslint/no-duplicate-enum-values"],
    conflicts: [],
    reviewTrigger: "Review if TypeScript changes enum runtime emission.",
  },
  {
    id: "typescript/no-extra-non-null-assertion",
    defectClass: "redundant chained non-null assertions",
    profile: "typescript-syntax",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Repeated assertions obscure intent without changing the type.",
    source: source("typescript/no-extra-non-null-assertion"),
    fixtures: fixture("typescript-syntax", 10, 26),
    replaces: ["@typescript-eslint/no-extra-non-null-assertion"],
    conflicts: [],
    reviewTrigger: "Review if TypeScript changes non-null assertion syntax.",
  },
  {
    id: "typescript/no-floating-promises",
    defectClass: "unhandled promise rejections",
    profile: "typescript-type-aware",
    executionPath: "native-type-aware",
    severity: "error",
    stability: "version-pinned",
    rationale: "Unhandled promises can fail after the caller has reported success.",
    source: source("typescript/no-floating-promises"),
    fixtures: fixture("typescript-type-aware", 5, 1),
    replaces: ["@typescript-eslint/no-floating-promises"],
    conflicts: [],
    reviewTrigger: "Review on any Oxlint, oxlint-tsgolint, or TypeScript version change.",
  },
  {
    id: "typescript/await-thenable",
    defectClass: "awaiting values that cannot settle asynchronously",
    profile: "typescript-type-aware",
    executionPath: "native-type-aware",
    severity: "error",
    stability: "version-pinned",
    rationale: "Awaiting a non-thenable often reveals a missing call or incorrect API type.",
    source: source("typescript/await-thenable"),
    fixtures: fixture("typescript-type-aware", 8, 3),
    replaces: ["@typescript-eslint/await-thenable"],
    conflicts: [],
    reviewTrigger: "Review on any Oxlint, oxlint-tsgolint, or TypeScript version change.",
  },
  {
    id: "typescript/switch-exhaustiveness-check",
    defectClass: "non-exhaustive switches over closed unions",
    profile: "typescript-type-aware",
    executionPath: "native-type-aware",
    severity: "error",
    stability: "version-pinned",
    rationale: "Exhaustive switches keep behavior aligned when a union gains a member.",
    source: source("typescript/switch-exhaustiveness-check"),
    fixtures: fixture("typescript-type-aware", 14, 11),
    replaces: ["@typescript-eslint/switch-exhaustiveness-check"],
    conflicts: [],
    reviewTrigger: "Review on any Oxlint, oxlint-tsgolint, or TypeScript version change.",
  },
  {
    id: "react/jsx-key",
    defectClass: "unstable identity for rendered list children",
    profile: "react",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Missing keys can associate component state with the wrong list item.",
    source: source("react/jsx-key"),
    fixtures: fixture("react", 2, 36, "tsx"),
    replaces: ["react/jsx-key", "@eslint-react/no-missing-key"],
    conflicts: [],
    reviewTrigger: "Review when React changes list reconciliation guidance.",
  },
  {
    id: "react/jsx-no-undef",
    defectClass: "undefined JSX component references",
    profile: "react",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "An undefined JSX identifier fails at render time.",
    source: source("react/jsx-no-undef"),
    fixtures: fixture("react", 6, 11, "tsx"),
    replaces: ["react/jsx-no-undef"],
    conflicts: [],
    reviewTrigger: "Review if the JSX runtime changes identifier resolution.",
  },
  {
    id: "react/rules-of-hooks",
    defectClass: "conditional or reordered React hook calls",
    profile: "react",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Hook call order must remain stable between renders.",
    source: source("react/rules-of-hooks"),
    fixtures: fixture("react", 11, 5, "tsx"),
    replaces: ["react-hooks/rules-of-hooks"],
    conflicts: [],
    reviewTrigger: "Review when React changes the Rules of Hooks.",
  },
  {
    id: "jsx-a11y/alt-text",
    defectClass: "images without an accessible text alternative",
    profile: "jsx-a11y",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Images need meaningful alternative text or explicit decorative intent.",
    source: source("jsx-a11y/alt-text"),
    fixtures: fixture("jsx-a11y", 2, 10, "tsx"),
    replaces: ["jsx-a11y/alt-text"],
    conflicts: [],
    reviewTrigger: "Review when JSX accessibility semantics or framework mappings change.",
  },
  {
    id: "node/no-exports-assign",
    defectClass: "CommonJS exports object reassignment",
    profile: "node",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Reassigning exports does not update module.exports.",
    source: source("node/no-exports-assign"),
    fixtures: fixture("node", 1, 1, "cjs"),
    replaces: ["n/no-exports-assign"],
    conflicts: [],
    reviewTrigger: "Review if Node.js changes CommonJS export semantics.",
  },
  {
    id: "node/no-path-concat",
    defectClass: "platform-dependent path concatenation",
    profile: "node",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "String concatenation with __dirname can create invalid cross-platform paths.",
    source: source("node/no-path-concat"),
    fixtures: fixture("node", 3, 14, "cjs"),
    replaces: ["n/no-path-concat"],
    conflicts: [],
    reviewTrigger: "Review if Node.js path APIs or rule semantics change.",
  },
  {
    id: "node/no-new-require",
    defectClass: "constructing through the CommonJS require function",
    profile: "node",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "require is a loader function, not a constructor.",
    source: source("node/no-new-require"),
    fixtures: fixture("node", 5, 12, "cjs"),
    replaces: ["n/no-new-require"],
    conflicts: [],
    reviewTrigger: "Review if Node.js changes CommonJS loader semantics.",
  },
  {
    id: "vitest/no-focused-tests",
    defectClass: "focused Vitest cases committed to the suite",
    profile: "vitest",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Focused tests silently skip most of the suite in CI.",
    source: source("vitest/no-focused-tests"),
    fixtures: fixture("vitest", 4, 10),
    replaces: ["vitest/no-focused-tests"],
    conflicts: ["jest/no-focused-tests"],
    reviewTrigger: "Review on Vitest major versions or native plugin changes.",
  },
  {
    id: "vitest/no-import-node-test",
    defectClass: "Node test-runner APIs mixed into a Vitest suite",
    profile: "vitest",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Mixing test runners bypasses Vitest lifecycle and configuration behavior.",
    source: source("vitest/no-import-node-test"),
    fixtures: fixture("vitest", 1, 34),
    replaces: ["vitest/no-import-node-test"],
    conflicts: [],
    reviewTrigger: "Review on Vitest or node:test interop changes.",
  },
  {
    id: "vitest/no-identical-title",
    defectClass: "duplicate Vitest case titles in one suite",
    profile: "vitest",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Unique titles make failures and filters unambiguous.",
    source: source("vitest/no-identical-title"),
    fixtures: fixture("vitest", 6, 8),
    replaces: ["vitest/no-identical-title"],
    conflicts: ["jest/no-identical-title"],
    reviewTrigger: "Review on Vitest major versions or native plugin changes.",
  },
  {
    id: "jest/no-focused-tests",
    defectClass: "focused Jest cases committed to the suite",
    profile: "jest",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Focused tests silently skip most of the suite in CI.",
    source: source("jest/no-focused-tests"),
    fixtures: fixture("jest", 6, 8),
    replaces: ["jest/no-focused-tests"],
    conflicts: ["vitest/no-focused-tests"],
    reviewTrigger: "Review on Jest major versions or native plugin changes.",
  },
  {
    id: "jest/no-jasmine-globals",
    defectClass: "legacy Jasmine globals in a Jest suite",
    profile: "jest",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Jasmine globals tie tests to an obsolete implementation detail of Jest.",
    source: source("jest/no-jasmine-globals"),
    fixtures: fixture("jest", 3, 9),
    replaces: ["jest/no-jasmine-globals"],
    conflicts: [],
    reviewTrigger: "Review on Jest test-runner architecture changes.",
  },
  {
    id: "jest/no-identical-title",
    defectClass: "duplicate Jest case titles in one suite",
    profile: "jest",
    executionPath: "native",
    severity: "error",
    stability: "stable",
    rationale: "Unique titles make failures and filters unambiguous.",
    source: source("jest/no-identical-title"),
    fixtures: fixture("jest", 7, 8),
    replaces: ["jest/no-identical-title"],
    conflicts: ["vitest/no-identical-title"],
    reviewTrigger: "Review on Jest major versions or native plugin changes.",
  },
  {
    id: "eslint/no-warning-comments",
    defectClass: "unresolved TODO markers left by assisted development",
    profile: "ai",
    executionPath: "native",
    severity: "warning",
    stability: "stable",
    rationale: "Visible TODO markers keep provisional generated code from becoming invisible debt.",
    source: source("eslint/no-warning-comments"),
    fixtures: fixture("ai", 1, 1),
    replaces: ["eslint/no-warning-comments"],
    conflicts: [],
    reviewTrigger: "Review when the AI profile gains a more specific native defect signal.",
  },
  {
    id: "react/react-compiler",
    defectClass: "React code rejected by the experimental compiler",
    profile: "react-compiler",
    executionPath: "native-experimental",
    severity: "warning",
    stability: "experimental",
    rationale: "Compiler diagnostics are useful migration evidence but are not stable enough for defaults.",
    source: source("react/react-compiler"),
    fixtures: fixture("react-compiler", 2, 17, "tsx"),
    replaces: ["react-hooks/react-compiler"],
    conflicts: [],
    reviewTrigger: "Review every Oxlint or React Compiler upgrade before promoting the rule.",
  },
] satisfies readonly RuleLedgerEntry[];

export const ruleLedger = validateRuleLedger(entries);
